Fix build errors on host due to macro __unused
In file included from system/media/audio_utils/tests/variadic_tests.cpp:22:
In file included from external/googletest/googletest/include/gtest/gtest.h:62:
In file included from external/googletest/googletest/include/gtest/internal/gtest-internal.h:40:
In file included from external/googletest/googletest/include/gtest/internal/gtest-port.h:263:
In file included from prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/sysroot/usr/include/x86_64-linux-gnu/sys/stat.h:106:
prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/sysroot/usr/include/x86_64-linux-gnu/bits/stat.h:106:31: error: expected member name or ';' after declaration specifiers
    __syscall_slong_t __unused[3];
    ~~~~~~~~~~~~~~~~~         ^
prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/sysroot/usr/include/x86_64-linux-gnu/bits/stat.h:164:31: error: expected member name or ';' after declaration specifiers
    __syscall_slong_t __unused[3];
    ~~~~~~~~~~~~~~~~~         ^
2 errors generated.

Test: build on host
Change-Id: Ia876e7c007386e9cd81367c8e6bdb007962c15fc